-- Initial Example Data For Application

-- Departments
INSERT INTO department (name) VALUES ('Human Resources');
INSERT INTO department (name) VALUES ('Marketing');
INSERT INTO department (name) VALUES ('Sales');
INSERT INTO department (name) VALUES ('Business Development');
INSERT INTO department (name) VALUES ('Research and Development');
INSERT INTO department (name) VALUES ('Training');
INSERT INTO department (name) VALUES ('Engineering');
INSERT INTO department (name) VALUES ('IT');
INSERT INTO department (name) VALUES ('Legal');
INSERT INTO department (name) VALUES ('Accounting');

-- Employees
INSERT INTO employee (name, email, department_id) VALUES ('Kandace Boase', 'kboase0@jiathis.com', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Val Siggee', 'vsiggee1@washington.edu', 6);
INSERT INTO employee (name, email, department_id) VALUES ('Kort Ledgister', 'kledgister2@nature.com', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Luelle Siddaley', 'lsiddaley3@unc.edu', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Robenia Ashby', 'rashby4@facebook.com', 6);
INSERT INTO employee (name, email, department_id) VALUES ('Jinny Hamments', 'jhamments5@creativecommons.org', 5);
INSERT INTO employee (name, email, department_id) VALUES ('Ulric Gaine of England', 'ugaine6@umn.edu', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Anna-diane Ameer-Beg', 'aameerbeg7@exblog.jp', 9);
INSERT INTO employee (name, email, department_id) VALUES ('Elset Domenichini', 'edomenichini8@si.edu', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Charlotte Monks', 'cmonks9@jigsy.com', 3);
INSERT INTO employee (name, email, department_id) VALUES ('Asia Ludgate', 'aludgatea@lulu.com', 3);
INSERT INTO employee (name, email, department_id) VALUES ('Calli Feavearyear', 'cfeavearyearb@weibo.com', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Celestine Duthy', 'cduthyc@nps.gov', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Gwenore Corbet', 'gcorbetd@cbslocal.com', 6);
INSERT INTO employee (name, email, department_id) VALUES ('Gweneth Showering', 'gshoweringe@guardian.co.uk', 5);
INSERT INTO employee (name, email, department_id) VALUES ('Gerry Setchfield', 'gsetchfieldf@unicef.org', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Aurelia Pinckney', 'apinckneyg@imdb.com', 9);
INSERT INTO employee (name, email, department_id) VALUES ('Kaiser Trimbey', 'ktrimbeyh@vimeo.com', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Jerrine Benadette', 'jbenadettei@mayoclinic.com', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Borg Crinage', 'bcrinagej@diigo.com', 9);
INSERT INTO employee (name, email, department_id) VALUES ('Sergent Gaynsford', 'sgaynsfordk@blogger.com', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Aretha Torrisi', 'atorrisil@adobe.com', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Livvy McIlvaney', 'lmcilvaneym@ihg.com', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Claus Braunthal', 'cbraunthaln@techcrunch.com', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Wayne Drewry', 'wdrewryo@google.nl', 6);
INSERT INTO employee (name, email, department_id) VALUES ('Shaun Durnian', 'sdurnianp@ameblo.jp', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Devlen Mordey', 'dmordeyq@timesonline.co.uk', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Raven Joriot', 'rjoriotr@opensource.org', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Gabrielle Eddis', 'geddiss@jigsy.com', 6);
INSERT INTO employee (name, email, department_id) VALUES ('Madison Schankelborg', 'mschankelborgt@mozilla.org', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Celisse January 1st', 'cjanuaryu@omniture.com', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Waylin Sleney', 'wsleneyv@jimdo.com', 3);
INSERT INTO employee (name, email, department_id) VALUES ('Joleen Satchel', 'jsatchelw@yandex.ru', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Arliene Tudgay', 'atudgayx@umich.edu', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Claudia Zouch', 'czouchy@ning.com', 3);
INSERT INTO employee (name, email, department_id) VALUES ('Cirilo Goding', 'cgodingz@ucoz.com', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Nadia Shillaber', 'nshillaber10@ucla.edu', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Ivie Javes', 'ijaves11@spiegel.de', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Janna Warfield', 'jwarfield12@indiegogo.com', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Marlo Gallen', 'mgallen13@diigo.com', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Henka Belcham', 'hbelcham14@zimbio.com', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Liana Joselevitz', 'ljoselevitz15@hatena.ne.jp', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Steffane Scarf', 'sscarf16@va.gov', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Marcella Cadreman', 'mcadreman17@utexas.edu', 9);
INSERT INTO employee (name, email, department_id) VALUES ('James Ivoshin', 'jivoshin18@hostgator.com', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Hugh Oakshott', 'hoakshott19@gravatar.com', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Maggie Chorlton', 'mchorlton1a@drupal.org', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Ashia Metts', 'ametts1b@chronoengine.com', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Hi Terney', 'hterney1c@boston.com', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Parsifal Metham', 'pmetham1d@blogger.com', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Wendy Ickov', 'wickov1e@unicef.org', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Filip Iban', 'fiban1f@gravatar.com', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Hamlin Overton', 'hoverton1g@unc.edu', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Dame Kock', 'dkock1h@census.gov', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Bran Eaglestone', 'beaglestone1i@npr.org', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Kane Aleso', 'kaleso1j@photobucket.com', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Joline Pardal', 'jpardal1k@usa.gov', 5);
INSERT INTO employee (name, email, department_id) VALUES ('Corena Friedlos', 'cfriedlos1l@github.io', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Pearline Sikora', 'psikora1m@ifeng.com', 5);
INSERT INTO employee (name, email, department_id) VALUES ('Tony Cowterd', 'tcowterd1n@amazon.com', 8);
INSERT INTO employee (name, email, department_id) VALUES ('Aimee Hutt', 'ahutt1o@accuweather.com', 5);
INSERT INTO employee (name, email, department_id) VALUES ('Gherardo Marchington', 'gmarchington1p@g.co', 7);
INSERT INTO employee (name, email, department_id) VALUES ('Any Francke', 'afrancke1q@dedecms.com', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Calvin Fairbrace', 'cfairbrace1r@tumblr.com', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Rosabella McRill', 'rmcrill1s@amazon.de', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Pepe Torvey', 'ptorvey1t@multiply.com', 2);
INSERT INTO employee (name, email, department_id) VALUES ('Nerissa Kilner', 'nkilner1u@mediafire.com', 1);
INSERT INTO employee (name, email, department_id) VALUES ('Dillie Bleiman', 'dbleiman1v@bluehost.com', 10);
INSERT INTO employee (name, email, department_id) VALUES ('Ines Moyes', 'imoyes1w@soup.io', 4);
INSERT INTO employee (name, email, department_id) VALUES ('Helenelizabeth Genney', 'hgenney1x@dot.gov', 7);
